# Generated by Django 4.0.6 on 2022-07-15 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=4000)),
                ('categoria', models.CharField(choices=[('TERROR', 'Terror'), ('SUSPENSE', 'Supense'), ('ANIMACAO', 'Animação'), ('ACAO', 'Ação'), ('OUTROS', 'Outros')], max_length=20)),
                ('vizualizacoes', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('thumb', models.ImageField(upload_to='thumb_filmes')),
            ],
        ),
    ]
