# Generated by Django 4.0.6 on 2022-07-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_episodio_temporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='tipo',
            field=models.CharField(choices=[('FILME', 'Filme'), ('SERIE', 'Série')], default='#', max_length=30),
        ),
    ]
